In [1]:
import numpy as np

Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [2]:
a = np.zeros(10)
a[4] =  1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
a = int(input("Enter a row: "))
b = int(input("Enter a column: "))
c = np.random.random((a,b))
print(c)
print('Avg of array c: ', np.mean(c))

[[0.720289   0.91738251 0.11393458 0.69256621]
 [0.28544196 0.5894848  0.18630777 0.46602161]
 [0.3504235  0.91098779 0.72364375 0.97562662]
 [0.01534266 0.95339805 0.2518315  0.30950198]]
Avg of array c:  0.5288865194957086


Q-3 Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-

[[1,1,1,1],

[1,0,0,1],

[1,0,0,1],

[1,1,1,1]]

In [4]:
def array(a,b):
    arr = np.ones((a,b))
    arr[1:-1,1:-1] = 0
    return arr
c = array(4,4)
print(c)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [5]:
a = np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

Answer. No, A true identity matrix cannot have shape 3×4 because identity matrices must be square

Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [9]:
a = np.zeros((5,5))
a = a + np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

point = np.array([2,3])

In [18]:
a = np.random.randint(1,101,20).reshape(10,2)
print('Coordinates of array:\n', a)
point = np.array([2,3])
# Euclidean Distance
Distances = np.sqrt(np.sum((a - point)**2, axis = 1))
# Convert Distances into Integer
Distance_int = Distances.astype(int)
print('Distance between points:', Distance_int)

Coordinates of array:
 [[67  1]
 [32 40]
 [46 76]
 [77 65]
 [24 88]
 [22 58]
 [22 67]
 [53  9]
 [ 9 56]
 [55 27]]
Distance between points: [65 47 85 97 87 58 67 51 53 58]


Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
a = np.arange(336).reshape(6,7,8)
index = np.where(a==99)
print(index)

(array([1]), array([5]), array([3]))


Q-9: Elements count-:
 Count the number of elements of a numpy array.

Example 1:

Input:

np.array([])

Output:

elements_count :  0

Example 2:

Input:

np.array([1, 2])

Output:

elements_count :  2

In [19]:
a = np.array(input('Enter list elements: ').split(), dtype=int)
print(a)
print('No. of elements in numpy array: ', a.size)

[1 4 6 8 0 5]
No. of elements in numpy array:  6


Q-10: Arrays
You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

Input Format:

A single line of input containing space separated numbers.

Output Format:

Print the reverse NumPy array with type float.

Example 1:

Input:

1 2 3 4 -8 -10

Output:

[-10.  -8.   4.   3.   2.   1.]

In [22]:
a = np.array(input('Enter list elements: ').split(), dtype=float)
print(np.flip(a))

[-10.  -8.   4.   3.   2.   1.]
