In [1]:
import numpy as np

Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [2]:
a = np.zeros(10)
a[4] =  1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
a = int(input("Enter a row: "))
b = int(input("Enter a column: "))
c = np.random.random((a,b))
print(c)
print('Avg of array c: ', np.mean(c))

[[0.720289   0.91738251 0.11393458 0.69256621]
 [0.28544196 0.5894848  0.18630777 0.46602161]
 [0.3504235  0.91098779 0.72364375 0.97562662]
 [0.01534266 0.95339805 0.2518315  0.30950198]]
Avg of array c:  0.5288865194957086


Q-3 Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-

[[1,1,1,1],

[1,0,0,1],

[1,0,0,1],

[1,1,1,1]]

In [7]:
def array(a,b):
    return np.ones((a,b))
c = array(4,4)
c[1:3,1:3] = 0
print(c)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [8]:
a = np.random.random(10)
print(a)

[0.53246002 0.44253245 0.27211744 0.60317905 0.96253142 0.12813297
 0.73372002 0.58508685 0.76922929 0.34461097]


Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

Answer. No, A true identity matrix cannot have shape 3×4 because identity matrices must be square

Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [9]:
a = np.zeros((5,5))
a = a + np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
